### ISSUE TITLE
Queries passing through all columns fail

### ISSUE THREAD

**Issue by alexander-held** [iris-hep/func_adl_servicex#50]
I am trying to do a query passing through all columns. This works fine with `func_adl_uproot`:
```python
from func_adl_uproot import UprootDataset
ds = UprootDataset("nanoaod15.root", "Events")
ds.value()
```
It does not work with `func_adl_servicex`:
```python
import servicex
from func_adl_servicex import ServiceXSourceUpROOT

dataset_name = ["https://xrootd-local.unl.edu:1094//store/user/AGC/nanoAOD/nanoaod15.root"]
sx_dataset = servicex.ServiceXDataset(dataset_name, "uproot")
ds = ServiceXSourceUpROOT(sx_dataset, "Events")
ds.value()
```
This crashes with
```
Transform be73e06d-0c92-46e5-8b43-13ba009717d4 had 1 errors:
  Error transforming file: h
  -> error.
```
(see https://github.com/ssl-hep/ServiceX/issues/408). The query succeeds when using `ds.Select(lambda e: e.Jet_pt).value()` instead.

The file being used is equivalent in both cases. I am using the following versions of libraries:
```
func-adl             3.0
func-adl-servicex    2.0
func-adl-uproot      1.9.0
servicex             2.5.4
```

**Comment by gordonwatts** [comment]
This almost certainly is not a bug in this package, but let's start from here.

**Comment by alexander-held** [comment]
I just ran this again with https://uproot-atlas.servicex.af.uchicago.edu/ and it succeeded with the same library versions. Perhaps the issue I saw was endpoint specific (I unfortunately do not remember which I used), but at the time that seemed unlikely to me as the query did work when specifying the column against the same endpoint.

**Comment by gordonwatts** [comment]
I just tested this again today, and it seems to work on the `af` backend. So I'm going to call this "not reproducable" - and if it comes up again, we should re-open!
